### ISSUE TITLE
启动 panda-dict 导致 ESC 键失效

### ISSUE THREAD

**Issue by tisfeng** [KrisLee1/panda-dict#1]
不知道是怎么实现的，反正感觉就挺神奇，发现启动 panda-dict 后就会导致 ESC 键失效。。一开始还以为是别的原因，后面尝试多次后发现，就是 panda-dict 导致，关闭后就正常了 😓

设备：Apple M1 Pro
系统：macOs Ventura 13.0 Beta版(22A5358e)

**Comment by KrisLee1** [comment]
非常感谢提出问题！应该是截图窗口Esc退出的问题，我修改好后推送。

**Comment by KrisLee1** [comment]
已经修复了。

**Comment by tisfeng** [comment]
ok
